### ISSUE TITLE
Program encounters error dealing with amino acids which aren't present in the target sequence.

### ISSUE THREAD

**Issue by orangebromeliad** [amarallab/NullSeq#1]
Hello,

Thank you for developing this program, I am currently trying to use it on a short protein sequence as a base. I have noticed that the program encounters the following error:

```
*************************
*   Welcome to NullSeq  *
*************************

***********************************************************************
Translation Table:	11
Operating Mode:		Exisitng Sequence - AA
AAFreq :
		K 	 0.0091
		T 	 0.0137
		N 	 0.0137
		Y 	 0.0091
		I 	 0.0091
		A 	 0.0457
		L 	 0.0411
		S 	 0.0228
		G 	 0.0457
		M 	 0.0046
		V 	 0.0046
		H 	 0.5845
		E 	 0.0137
		D 	 0.1735
		P 	 0.0046
		R 	 0.0046
GC content :		48.6
Length :		200
Number of sequence :	10
***********************************************************************
Traceback (most recent call last):
  File "/Users/littlet/Downloads/NullSeq/nullseq.py", line 149, in <module>
    TT=args.TT, gc=args.GC, l=args.l, ES=args.m)
  File "/Users/littlet/Downloads/NullSeq/nullseq.py", line 92, in main
    GC=gc/100, length=length, n=N, nseq=number)
  File "/Users/littlet/Downloads/NullSeq/NullSeq_Functions.py", line 747, in get_Random_Nuc_Seq
    b = get_beta(GC, length, CodonforAA, AAFrequency, n)
  File "/Users/littlet/Downloads/NullSeq/NullSeq_Functions.py", line 521, in get_beta
    avl = compute_average_GC(rl, length, CforAA, setAAProb, n) - m
  File "/Users/littlet/Downloads/NullSeq/NullSeq_Functions.py", line 631, in compute_average_GC
    GCnumber.append(AAcount[AA]*sum([Probability[codon]*CodonGC[codon] \
KeyError: 'F'
```

I believe that this KeyError is due to the amino acid content, since there is no F residue present in the original sequence. When I add an F, the KeyError changes to:

`KeyError: 'C'`

I tried to correct the issue myself but my Python isn't fluent and I cannot find when the `AAcount` dictionary is being defined. I also don't understand how multiple lines of the code can encounter errors at once!!

I look forward to your response.

Best wishes,
Tim

**Comment by adamhockenberry** [comment]
Thanks for the post Tim. I'm one of the original authors and believe that I just fixed this issue.

Going to note a few things here. I did not accept your pull request as I felt there was a better way to solve the problem more generally. Please look through the code if you'd like, I added in a short function called "clean_AA_dict()" that essentially ensures that the amino acid frequency dictionary that we extract contains all of the amino acids indicated in the given translation table (that is provided in Biopython and which we extract in part using the "from Bio.Data import CodonTable" followed by our own "Codons_for_AA()" function). Basically any non-observed amino acid gets a frequency of zero rather than not being included in the dictionary now (which was causing your error). The nice thing about that is then it's easy to make sure that the observed amino acid frequency dictionary does not contain more keys (amino acids) beyond what is provided in the translation table. If so, this will exit with an assertion error and a (hopefully) helpful error message. In this way we don't have to define the "out-of-bounds" amino acids (B, O, etc.) manually and can instead just make sure that things match exactly to the NCBI codon tables

A few other things since you're using the software (and thank you so much for your feedback / input!):

1. I made a release of the original version of the code pre-any changes that I just made which corresponds to the code we used to produce our manuscript (Releases tab of the repo)
2. We also have a newer but not fully completed version 2.0 (see the top of the README for the link). In truth, it may never get completed but if I continue to work on this project I will likely make further changes there rather than here.
3. The new version of THIS repo, if you pull it should contain my updates and let me know if there are any issues/errors with that.
4. I haven't looked at this code in a while and the repo is not under active development, so if you anticipate making a lot of changes or working on this in the future please feel free to just "fork" the repo and make any changes that you see fit without having to ask / push. I'm hesitant to give outside access to the original repository since I want to ensure that it links up and works as the initial manuscript said it would/should
5. The problem with further development is that we didn't do much error testing in here (as you can probably see) and we just don't want the code to "break". If we had set up a more rigorous testing framework, we would be more willing to let outside collaboration because we could run any changes you make through some tests to ensure that we maintain all the proper results. It would be great if we could/would do that but it's just not currently on our minds at the moment so please feel free to just work with your own local version or a fork and cite us if you publish anything that you built off of this. I'm happy to see someone using it.
6. That said, if you do see outright errors (as opposed to new functionality) please let me know asap and I'll try to fix them.
7. I don't want any of this to discourage you from learning or from using the software! Far from it, I just don't want this repo to change too drastically past its intended/published mission. Lastly, I'll add that if you'd like to collaborate too I'd be happy to chat more about features you'd find useful, general coding/github questions, etc. Feel free to send me a private message if you have any questions (also on twitter @HockenberryAdam) and we can communicate more directly.

Hope the included changes in this recent push solve your current issues and thanks once again for reaching out and using the software.

**Comment by orangebromeliad** [comment]
Thank you for your comprehensive response!
